name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache Docker image and Jekyll site
        uses: actions/cache@v2
        with:
          path: |
            /srv/jekyll/vendor/bundle
            /srv/jekyll/.jekyll-cache
          key: ${{ runner.os }}-jekyll-${{ hashFiles('**/Gemfile.lock') }}-${{ github.run_number }}-${{ github.run_id }}-${{ now() }}

      - name: Build the site in the jekyll/builder container
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

